apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: node-exporter
spec:
  podMetricsEndpoints:
  - interval: 30s
    path: /metrics
    port: metrics
    honorLabels: true
  namespaceSelector:
    matchNames:
    - prj-install
  selector:
    matchLabels:
      app: node-exporter
