apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cadvisor
spec:
  podMetricsEndpoints:
  - interval: 30s
    path: /metrics
    port: http
    honorLabels: true
  namespaceSelector:
    matchNames:
    - prj-install
  selector:
    matchLabels:
      name: cadvisor
