apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: additional.yaml
  ruleSelector:
    matchLabels:
      role: prometheus-rules
  serviceAccountName: prometheus
  podMonitorSelector: {}
  podMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
  enableAdminAPI: false
