apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: prj-install
stringData:
  additional.yaml: |-
    - job_name: cadvisior
      static_configs:
      - targets:
        - "master:8080"
        - "node1:8080"
        - "node2:8080"
      metrics_path: '/metrics' 