apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: prj-install
stringData:
  additional.yaml: |-
    - job_name: cadvisior
      static_configs:
      - targets: ['http://113.31.106.132:8080/metrics']
      metrics_path: '/metrics' 