apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: prj-install
stringData:
  additional.yaml: |-
    - job_name: cadvisior
      static_configs:
      - targets:
        - "10.23.239.33:8080"
        - "10.23.144.128:8080"
        - "10.23.236.239:8080"
      metrics_path: '/metrics' 