apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: prj-install
stringData:
  prometheus-additional.yaml: |- 
    - job_name: All_Your_Namespace_Metrics
      static_configs:
      - targets: ['http://113.31.106.132:8080/metrics']
      metrics_path: '/metrics' 