apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: prometheus-rules
  name: cadvisior
spec:
  groups:
    - name: cadvisior
      rules:
      - alert: Pod CPU使用率超过80%
        expr: (sum(rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_name!=""}[2m])) by (container_label_io_kubernetes_pod_name, container_label_io_kubernetes_pod_namespace))/(sum(container_spec_cpu_quota) by (container_label_io_kubernetes_pod_name,container_label_io_kubernetes_pod_namespace)/10000000) > 80
        for: 1m
        labels:
          level: "P3"
          equal: "PodCPUUsage "
        annotations:
          summary: "Pod CPU 使用率"
          description: "%"
      - alert: Pod Memory使用率超过80%
        expr: floor((container_memory_usage_bytes{container_label_io_kubernetes_pod_name!="",image!=''} / container_spec_memory_limit_bytes{image!=''} > 0.8 and   container_memory_usage_bytes{image!=''} / container_spec_memory_limit_bytes{image!=''} < 2)*1000)/10
        for: 1m
        labels:
          level: "10"
          equal: "PodMemory"
        annotations:
          summary: "Pod 内存使用率"
          description: "%"
      - alert: PodStartFailed
        expr: kube_pod_status_phase{phase=~"Failed|Unknown"}==1
        for: 1m
        labels:
          level: "10"
          equal: "PodStartFailed"
        annotations:
          summary: "Pod 启动失败"
          description: ""