apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
spec:
  endpoints:
  - path: /metrics
    port: prometheus
    honorLabels: true
  selector:
    matchLabels:
      name: prometheus
